# values.yaml - All configurable values
replicaCount: 1

image:
  repository: gcr.io/gke-cluter/hello-world
  tag: "v1"
  pullPolicy: IfNotPresent

service:
  type: LoadBalancer
  port: 80
  targetPort: 80

resources:
  limits:
    cpu: 100m
    memory: 64Mi
  requests:
    cpu: 50m
    memory: 32Mi

# You can add more environments later:
# dev:
#   replicaCount: 1
# prod:
#   replicaCount: 3
